### ISSUE TITLE
Don't use 8.8.8.8 as resolver

### ISSUE THREAD

**Issue by Fusl** [CalumMc/OpenNIC-Whitelist-Updater#1]
Hi,

as 8.8.8.8 is blocked here for a good reason, the script never worked for me, but I found out at a later time that it uses 8.8.8.8 for resolving.

Instead of making the script configurable with only one IPv4 and only one IPv6 server, we should allow people to specify IPs in a space separated format.

All servers in the list then get queried for the IP of api.opennicproject.org, the resulting IP will be put in a list, it will be sorted how often the IPs appear and the highest one taken.

Example in bash:
```for server in $servers; do dig A api.opennicproject.org @"$server"; done | sort | uniq -c | sort -n | head -n1```

With that, we can ship the default configuration with some OpenNIC Tier2s (from different people) and also include servers like Google Public DNS, OpenDNS and whatsoever configured.

**Comment by CalumMc** [comment]
Hi,
I've added the functionality you describe, using the non-whitelist OpenNIC servers below as default.

IPv4	= 31.171.155.107 192.71.247.247 5.9.49.12 130.255.73.90 106.186.17.181
IPv6	= 2a03:f80:ed15:ca7:ea75:b12d:714:d234 2a01:4f8:161:4109::6 2a01:4f8:191:306c::2 2a00:dcc0:eda:88:245:71:858e:a15 2001:41d0:8:be92::1

Let me know if there are any issues.
