### ISSUE TITLE
Error Running Install

### ISSUE THREAD

**Issue by brads-git** [CalumMc/OpenNIC-Whitelist-Updater#3]
I ran the install and cron script:

`bash <(curl -s https://raw.githubusercontent.com/CalumMc/OpenNIC-Whitelist-Updater/master/install.sh)`

and received the following error:

`bash: /dev/fd/63: No such file or directory`

I don't see this directory in install.sh. The link _fd@_ exists in _/dev/_. Also _/proc/self/fd/_ contains only _0@_ _1@_ _2@_ and _3@_.

**Comment by CalumMc** [comment]
This was an issue caused by a recent change to the script. The issue was piping to bash running as root. I've updated the command in the readme. Let me know if there are any issues.
